Repository Galeon2098/CuidaME, pull requests merged in 2024-03, with the labels that each got.

#118 doc: task#114: estrategia de ramas
  cuidaMe-docs/docs/entregable-2/Estrategia de Ramas.md
  cuidaMe-docs/docs/entregable-2/img/img1.PNG
Labels: Documentacion

#111 feat: Integración continua #90 #91
  .github/workflows/django.yml
  local_settings.gactions.py
Labels: Fullstack

#124 feat: frontend nuevo para las vistas de listado, búsqueda, detalles y edición de ofertas
  main/offer/templates/offers/detail.html
  main/offer/templates/offers/edit_offer.html
  main/offer/templates/offers/list.html
  main/offer/templates/offers/myOffers.html
  main/offer/templates/offers/publish.html
  main/offer/templates/offers/search_results.html
  main/offer/urls.py
  main/offer/views.py
  main/static/css/base.css
Labels: Frontend

#120 doc: Migración a Docusaurus completa #93
  cuidaMe-docs/docs/Brainstorming de innovación.md
  cuidaMe-docs/docs/entregable-1/9-Análisis-de-Competidores.md
  cuidaMe-docs/docs/grupo.md
  cuidaMe-docs/docs/intro.md
  cuidaMe-docs/docs/reuniones/Registro de Actas de Reunión.md
  cuidaMe-docs/docs/reuniones/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-1--03_02/Informe reunión 03_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-1--03_02/Orden del Día 03_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-1--03_02/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-2--08_02/Acta reunión 08_02_24.md
  cuidaMe-docs/docs/reuniones/reunion-2--08_02/Orden del Día 08_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-2--08_02/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-3--14_02/Feedback draft 13-02-2024.md
  cuidaMe-docs/docs/reuniones/reunion-3--14_02/Orden del Día 14_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-3--14_02/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-4--18_02/Acta reunión 18_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-4--18_02/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-5--25_02/Feedback de clase 20-02-2024.md
  cuidaMe-docs/docs/reuniones/reunion-5--25_02/Orden del Día 21_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-5--25_02/_category_.json
  cuidaMe-docs/docs/reuniones/reunion-6--28_02/ draft FEEDBACK CLASE 27_02.md
  cuidaMe-docs/docs/reuniones/reunion-6--28_02/Orden del Día 28_02_2024.md
  cuidaMe-docs/docs/reuniones/reunion-6--28_02/_category_.json
  cuidaMe-docs/docs/subgrupos/_category_.json
  cuidaMe-docs/docs/subgrupos/análisis/9-Diagrama UML.md
  cuidaMe-docs/docs/subgrupos/análisis/Diagramas de secuencia.md
  cuidaMe-docs/docs/subgrupos/análisis/_category_.json
  cuidaMe-docs/docs/subgrupos/análisis/diagrama_clases.md
  cuidaMe-docs/docs/subgrupos/análisis/diagrama_gantt.md
  cuidaMe-docs/docs/subgrupos/análisis/img/diagrama-uml.jpeg
  cuidaMe-docs/docs/subgrupos/análisis/img/diagrama_clases.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagrama_gantt_completo.jpg
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-01.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-02.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-03.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-04.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-05.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-06.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-07.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-08.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-09.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-10.png
  cuidaMe-docs/docs/subgrupos/análisis/img/diagramas-secuencias/cuc-11.png
  cuidaMe-docs/docusaurus.config.js
  cuidaMe-docs/src/pages/index.js
Labels: Documentacion

#183 Task#177 frontend
  cuidaMe-docs/docs/entregable-2/Estrategia de Ramas.md
  cuidaMe-docs/docs/entregable-2/img/img1.PNG
  main/offer/templates/offers/detail.html
  main/offer/templates/offers/publish.html
Labels: Bug, Frontend, Grupo 3

#192 Task#176: Arreglos barra de navegación
  main/offer/templates/offers/list.html
  main/static/css/base.css
  main/templates/main/base.html
Labels: Bug, Frontend, Grupo 3

#194 Task#188: Correcciones
  cuidaMe/forms.py
  cuidaMe/settings.py
  main/models.py
  main/offer/templates/offers/publish.html
  main/static/Images/portadaPrincipal.jpg
  main/static/css/base.css
  main/static/css/profile.css
  main/templates/main/base.html
  main/templates/main/cliente_edit.html
  main/templates/main/edit_profile.html
  main/templates/main/my_profile_detail.html
  main/templates/main/startPage.html
  main/templates/registration/login.html
  main/templates/registration/register_cliente.html
  main/templates/registration/register_cuidador.html
  main/tests.py
Labels: Bug, Frontend, Backend, Grupo 3

#198 feat: Frontend de lista, creación y detalles de hilos y comentarios #160
  .gitignore
  main/foro/forms.py
  main/foro/templates/comment_form.html
  main/foro/templates/list_threads.html
  main/foro/templates/new_thread.html
  main/foro/templates/thread_detail.html
  main/foro/urls.py
  main/models.py
  main/offer/templates/offers/publish.html
  main/offer/urls.py
  main/offer/views.py
  main/static/css/base.css
  main/templates/main/base.html
Labels: Frontend, Grupo 1
